FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Copy the backend directory contents into the container at /app
COPY backend/ /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run the app when the container launches
ENTRYPOINT ["python", "app.py"]
