name: MSDO
on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]
jobs:
  sample:
    name: Microsoft Security DevOps

    # Windows and Linux agents are supported
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write
      actions: read
      # Write access for security-events is only required for customers looking for MSDO results to appear in the codeQL security alerts tab on GitHub (Requires GHAS)
      security-events: write
      packages: write

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v3
    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: 'ghcr.io'
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      # Build Docker image
    # - name: Build Docker image
    #   run: |
    #     docker build -t my-frontend:latest .
    #     docker tag my-frontend:latest 
    - name: Build and Push API Image to Github
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        tags: |
          ghcr.io/innocentbear/my-frontend:latest
        push: true
      # Run analyzers
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@latest
      id: msdo
      env:
        GDN_TRIVY_ACTION: image
        GDN_TRIVY_TARGET: ghcr.io/innocentbear/my-frontend:latest
        GDN_TRIVY_SEVERITIES : HIGH,CRITICAL
      # GDN_RUN_LOGGERLEVEL: verbose
      with:
      # config: string. Optional. A file path to an MSDO configuration file ('*.gdnconfig').
      # policy: 'GitHub' | 'microsoft' | 'none'. Optional. The name of a well-known Microsoft policy. If no configuration file or list of tools is provided, the policy may instruct MSDO which tools to run. Default: GitHub.
      # categories: string. Optional. A comma-separated list of analyzer categories to run. Values: 'code', 'artifacts', 'IaC', 'containers'. Example: 'IaC, containers'. Defaults to all.
      # languages: string. Optional. A comma-separated list of languages to analyze. Example: 'javascript,typescript'. Defaults to all.
        tools: trivy,bandit,checkov,eslint,terrascan

      # Upload alerts to the Security tab - required for MSDO results to appear in the codeQL security alerts tab on GitHub (Requires GHAS)
    - name: Upload alerts to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
       sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      # Upload alerts file as a workflow artifact - required for MSDO results to appear in the codeQL security alerts tab on GitHub (Requires GHAS)
    - name: Upload alerts file as a workflow artifact
      uses: actions/upload-artifact@v4
      with:  
       name: alerts
       path: ${{ steps.msdo.outputs.sarifFile }}
